inherit: true

build:
  nodes:
    analysis:
      environment:
        node: v10.14.2
      tests:
        override: [php-scrutinizer-run]

checks:
  php:
    code_rating: true
    duplication: true

filter:
  paths: [src/*, tests/*]
