language: php

dist: xenial

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: '7.1'
      env: DB=MYSQL CORE_RELEASE=3.7
    - php: '7.2'
      env: DB=MYSQL CORE_RELEASE=3.7
    - php: '7.3'
      env: DB=MYSQL CORE_RELEASE=3.7

before_script:
  - composer self-update || true
  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
  - vendor/bin/phpunit agency-extensions/tests
