mappings:
  CarouselPageExtension: CWP\AgencyExtensions\Extensions\CarouselPageExtension
  CWPBaseHomePageExtension: CWP\AgencyExtensions\Extensions\CWPBaseHomePageExtension
  CWPPageExtension: CWP\AgencyExtensions\Extensions\CWPPageExtension
  CWPSiteConfigExtension: CWP\AgencyExtensions\Extensions\CWPSiteConfigExtension
  DefaultThemeExtension: CWP\AgencyExtensions\Extensions\DefaultThemeExtension
  CwpThemeHelper: CWP\AgencyExtensions\Helper\CwpThemeHelper
  CarouselItem: CWP\AgencyExtensions\Model\CarouselItem
  CwpThemeHelperTest: CWP\AgencyExtensions\Tests\Helper\CwpThemeHelperTest
  CWPCarouselItemExtensionTest: CWP\AgencyExtensions\Tests\Extensions\CWPCarouselItemExtensionTest
  CWPSiteConfigExtensionTest: CWP\AgencyExtensions\Tests\Extensions\CWPSiteConfigExtensionTest
  DefaultThemeExtensionTest: CWP\AgencyExtensions\Tests\Extensions\DefaultThemeExtensionTest
  DefaultThemeExtensionStub: CWP\AgencyExtensions\Tests\Extensions\Stub\DefaultThemeExtensionStub
