---
Name: CwpNewThemeConfig
After:
  - 'framework/*'
  - 'cms/*'
---

SiteConfig:
  extensions:
    - CWPSiteConfigExtension

SiteTree:
  extensions:
    - CWPSiteTreeLanguageExtention
Form:
  extensions:
    - CWPFormExtension

FormField:
  extensions:
    - CWPFormFieldExtension

Page_Controller:
  extensions:
    - CWPPageExtension

BasePage:
  extensions:
    - CWPBasePageExtension

CWPSearchController:
  page_limit: 10

CarouselItem:
  extensions:
    - CWPCarouselItemExtension

DatedUpdateHolder:
  extensions:
    - CWPDatedUpdateHolderExtension

UserDefinedForm:
  extensions:
    - CWPUserDefinedFormExtension

Director:
  rules:
    search: 'CWPSearchController'
