---
Name: CwpNewThemeConfig
After:
  - 'framework/*'
  - 'cms/*'
---

SiteConfig:
  extensions:
    - CWPCleanupSiteConfigExtension

SiteTree:
  extensions:
    - CWPSiteTreeLanguageExtention

FormField:
  extensions:
    - CWPFormFieldExtension

Page_Controller:
  extensions:
    - CWPPageExtension

CWPSearchController:
  page_limit: 10

Director:
  rules:
    search: 'CWPSearchController'
