---
Name: agencyextensionsconfig
---
CWP\CWP\PageTypes\BaseHomePage:
  extensions:
    - CWP\AgencyExtensions\Extensions\CarouselPageExtension

PageController:
  extensions:
    - CWP\AgencyExtensions\Extensions\CWPPageExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - CWP\AgencyExtensions\Extensions\CWPSiteConfigExtension

---
Except:
  envVarSet: CWP_AGENCY_DISABLE_FONTAWESOME_PLUGIN
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
SilverStripe\Forms\HTMLEditor\TinyMCEConfig:
  editor_css:
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
