---
Name: agencyextensionsconfig
---
CWP\CWP\PageTypes\BaseHomePage:
  extensions:
    - CWP\AgencyExtensions\Extensions\CarouselPageExtension

PageController:
  extensions:
    - CWP\AgencyExtensions\Extensions\CWPPageExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - CWP\AgencyExtensions\Extensions\CWPSiteConfigExtension
