---
Name: agencyextensionsconfig
---
BaseHomePage:
  extensions:
    - CarouselPageExtension
    - CWPBaseHomePageExtension

BasePage_Controller:
  extensions:
    - DefaultThemeExtension

Security:
  extensions:
    - DefaultThemeExtension

Page_Controller:
  extensions:
    - CWPPageExtension

SiteConfig:
  extensions:
    - CWPSiteConfigExtension
