---
Name: CwpNewThemeConfig
---
SiteConfig:
  extensions:
    - CWPSiteConfigExtension
SiteTree:
  extensions:
    - CWPSiteTreeLanguageExtention
Page_Controller:
  extensions:
    - CWPPageExtension
