---
Name: agencyextensionsconfig
---
CWP\CWP\PageTypes\BaseHomePage:
  extensions:
    - CWP\AgencyExtensions\Extensions\CarouselPageExtension
    - CWP\AgencyExtensions\Extensions\CWPBaseHomePageExtension

CWP\CWP\PageTypes\BasePageController:
  extensions:
    - CWP\AgencyExtensions\Extensions\DefaultThemeExtension

SilverStripe\Security\Security:
  extensions:
    - CWP\AgencyExtensions\Extensions\DefaultThemeExtension

PageController:
  extensions:
    - CWP\AgencyExtensions\Extensions\CWPPageExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - CWP\AgencyExtensions\Extensions\CWPSiteConfigExtension
