---
Name: CwpNewThemeConfig
After:
  - 'framework/*'
  - 'cms/*'
---

SiteConfig:
  extensions:
    - CWPCleanupSiteConfigExtension

SiteTree:
  extensions:
    - CWPSiteTreeLanguageExtention

FormField:
  extensions:
    - CWPFormFieldExtension
