---
Name: CwpNewThemeConfig
After:
  - 'framework/*'
  - 'cms/*'
---

SiteConfig:
  extensions:
    - CWPSiteConfigExtension

SiteTree:
  extensions:
    - CWPSiteTreeLanguageExtention
Form:
  extensions:
    - CWPFormExtension

FormField:
  extensions:
    - CWPFormFieldExtension

Page_Controller:
  extensions:
    - CWPPageExtension

CWPSearchController:
  page_limit: 10

CarouselItem:
  extensions:
    - CWPCarouselItemExtension

Director:
  rules:
    search: 'CWPSearchController'
